# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop/cop/internal_affairs

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - "config/initializers/devise.rb"
    - "db/schema.rb"
  TargetRubyVersion: 2.4
  RSpec:
    Patterns:
      - '_test.rb$'

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"

Lint/InterpolationCheck:
  Exclude:
    - "spec/**/*.rb"

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - "def_matcher"
    - "def_node_matcher"

Lint/BooleanSymbol:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"

Performance/Caller:
  Exclude:
    - spec/rubocop/cop/performance/caller_spec.rb

RSpec/PredicateMatcher:
  EnforcedStyle: explicit